@startuml
sprite $celery [99x40/16] {
77777777777777789abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccb9777
7777777777779bdeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddefffffffd87
77777777779ceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedefffffffffffd8
777777778ceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffffffffffffa
77777779deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedffffffffffffffffc
777777aeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedfffffffffffffffffc
77777aeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedffffffffffffffffffb
77779eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedfffffffffffffffffff8
7778eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedfffffffffffffffffffa7
777ceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffffffffffffffffda77
779ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffdba987777
77cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffc8777777777
79ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffa77777777777
7bdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeffffffffffa777777777777
8ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffc7777777777777
9ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffff87777777777777
addddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffc77777777777777
bdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddefffffffffa77777777777777
bdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddefffffffff877777777777777
cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffff877777777777777
ceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffffffff877777777777777
ceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffffffff877777777777777
beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffffffffa77777777777777
aeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedfffffffffc77777777777777
9eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedffffffffff87777777777777
8eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffffffffc7777777777777
7ceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffffffffa777777777777
79eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedfffffffffffb77777777777
78deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffffffffffd9777777777
779ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffdba987777
777cdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddefffffffffffffffffea77
7778ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffb7
77779ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffff9
77777addddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffb
777777addddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffc
77777779ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffc
777777778cddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffa
77777777779cddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffd8
7777777777779bddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddefffffffc87
7777777777777778aabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcb9777
}
@enduml
